### ISSUE TITLE
Option for model, not to invalidate collection tag, if new objects does not have specific columns with values set

### ISSUE THREAD

**Issue by fruit** [fruit/sfCacheTaggingPlugin#11]
Example: Useful when you create new object with `is_enabled = false`, this object will temporary not display in front-end, but in back-end listing should not be cached.

```
ModelName:
  Cachetaggable:
    defaultValuesInNewObjectSkipsCollectionInvalidation:
      is_enabled: false
      publish_on: null
```
