### ISSUE TITLE
Support the build-in behavior NestedSet

### ISSUE THREAD

**Issue by fruit** [fruit/sfCacheTaggingPlugin#14]
Check for bugs, problems, errors when model has `NestedSet` behavior with plugin's behavior `Cachetaggable`.

```
  MyModel:
    actAs:
      Cachetaggable: ~
      NestedSet: ~
```
